name: Deploy Docker Compose Application

on:
  push:
    branches:
      - main  # Set this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
         
    - name: Decode SSH
      env:
          SSH_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      run: mkdir ~/.ssh && echo $SSH_KEY | base64 --decode >~/.ssh/ssh_key

    - name: Change Permission of ssh file
      run: chmod 600 ~/.ssh/ssh_key

    - name: Add key to known host
      run: ssh-keyscan -H ${{ secrets.GCP_VM_PRODUCTION_IP }}  >> ~/.ssh/known_hosts
    - name: Docker build
      run: |
        ssh -i ~/.ssh/ssh_key ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_PRODUCTION_IP }} << "EOF"
          echo "Current directory"
          pwd
          cd /home/badal_shrestha/comitee-ml
          docker ps
          git stash
          git pull
          docker image prune -f
          docker compose up --build -d 
          docker system prune -f
        EOF

    - name: Send custom JSON data to Slack workflow
      id: slack
      if: success()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "text": "Production deployment sucess"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Send failure message
      id: slack_failure
      if: failure()
      uses: slackapi/slack-github-action@v1.26.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "text": "Production deployment failed"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
